# _config.yml
title: QRCards
description: Quick links to my loyalty cards.
author: Louis Giron
baseurl: "/QRCards"  # leave empty for user sites
url: "" # leave empty for GitHub Pages to set automatically
