# _config.yml
title: QR Codes
description: Quick links to my loyalty cards.
author: Louis Giron
baseurl: "/qrcodes"  # leave empty for user sites
url: "" # leave empty for GitHub Pages to set automatically
